events {
    worker_connections 1024;
}

http {
    upstream flask_backend {
        server flasker:5021;  # Use the Flask service name
    }

    server {
        listen 80;

	location / {
            proxy_pass http://flask_backend;
        }
	location /squared {
            proxy_pass http://flask_backend;
        }
	

    }
}
