services:
#this will need to change when I create the apps
  player-report:
    build:
      context: ./playerReport
      dockerfile: Dockerfile
    expose:
      - "5005"
  player-bio:
    build:
      context: ./playerBio
      dockerfile: Dockerfile
    expose:
      - "5005"
  player-batting:
    build:
      context: ./playerBatting
      dockerfile: Dockerfile
    expose:
      - "5005"
  player-fielding-pitching:
    build:
      context: ./playerFieldingPitching
      dockerfile: Dockerfile
    expose:
      - "5005"
  team-report:
    build:
      context: ./teamReport
      dockerfile: Dockerfile
    expose:
      - "5005"
  team-info:
    build:
      context: ./teamInfo
      dockerfile: Dockerfile
    expose:
      - "5005"
  home-page:
    build:
      context: ./homePage
      dockerfile: Dockerfile
    expose:
      - "5005"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Bind host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx config
    depends_on:
      - player-report
      - player-bio
      - player-batting
      - player-fielding-pitching
      - team-report
      - team-info
      - home-page
      - redis
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
    redis_data:
      
