events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

	location /viewPlayer {
            proxy_pass http://player-report:5005/;
        }
    location / {
        proxy_pass http://player-report:5005/AddNewPlayer;
    }
    } 
}  
