events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
        proxy_pass http://player-report:5005/;
    }
	location /viewPlayer {
            proxy_pass http://player-report:5005/viewPlayer;
        }
    location /getPlayerBatting {
            proxy_pass http://player-batting:5005/getplayerBatting;
        }
    location /getPlayerBio {
            proxy_pass http://player-bio:5005/getplayerBio;
        }
    location /getPlayerFieldingandPitching {
            proxy_pass http://player-fielding-pitching:5005/getplayerFieldingPitching;
        }
    location /getTeamInfo {
            proxy_pass http://team-info:5005/getTeamInfo;
        }
    location /viewTeam {
            proxy_pass http://team-report:5005/;
        }
    } 
}  
