events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

	location / {
        #Will need to be changed but will work for now
            proxy_pass http://HOME:5005/;
        }
    }
}
