events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

	location /wind {
            proxy_pass http://wind:5005/;
        }
	location /temp {
            proxy_pass http://temp:5005/;
        }
    location /humidity {
            proxy_pass http://humidity:5005/;
        }
	location /weatherman {
            proxy_pass http://weatherman:5005/;
    }
    }
}
